comment_width = 100
doc_comment_code_block_width = 80
error_on_unformatted = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports= "StdExternalCrate"
imports_granularity = "Crate"
imports_layout= "HorizontalVertical"
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
wrap_comments = true
